### ISSUE TITLE
spring-boot-devtools should not be used on production

### ISSUE THREAD

**Issue by mpol** [openaire/metrics-delivery-endpoint#12]
Spring Boot developer tools are automatically disabled when running a fully packaged application (eg. using `java -jar`).
This can be overridden but it is not recommended.

From https://docs.spring.io/spring-boot/docs/2.5.4/reference/html/using.html#using.devtools

> This must not be done in a production environment where running devtools is a security risk.

We use `FileSystemWatcher` from devtools and should find a replacement.

**Comment by marekhorst** [comment]
Reimplementing to rely directly on the `WatchService`:

https://docs.oracle.com/javase/tutorial/essential/io/notification.html#overview

to avoid devtools involvement and purge this dependency.
