### ISSUE TITLE
Make logging configuration suitable for actual deployments easier

### ISSUE THREAD

**Issue by mpol** [openaire/metrics-delivery-endpoint#21]
The `logback-spring.xml` configuration currently in the project sets defaults that are not suitable for production deployment - log directory path relative to the current directory - or that should be left for the administrators to decide - log rotation policy.
They can be changed by using a complete new configuration file and pointing to it via a system property.

But most of these things can be also set using [application properties](https://docs.spring.io/spring-boot/docs/2.5.4/reference/htmlsingle/#features.logging.file-output), and actually the default of logging to standard output and handling persistence and rotation outside of the application is probably right for deployments on current systems.

So does the config file provide real value during development and needs to be acommodated or can we just get rid of it?

**Comment by mpol** [comment]
@marekhorst do you need `logback-spring.xml` for development?

**Comment by marekhorst** [comment]
> @marekhorst do you need `logback-spring.xml` for development?

Nah, it was just a starting point for logging config which seemed to be allowing the involvement of various loggers. If it would be easier to rely on application.properties then let's do this.
